use customer_shopping_behaviour;
SELECT * From customer limit 20;

-- Q1 What is the total revenue generated by make VS female customers.
SELECT gender,sum(purchase_amount) as revenue
FROM customer
GROUP BY gender;

-- Q2 Which customers used a discount but still spent more than the average purchase amount?
SELECT *
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount > (SELECT AVG(purchase_amount) 
FROM customer);

-- Q3 Which are the top 5 products with the highest average review rating?
SELECT item_purchased, round(AVG(review_rating),2) as 'Average Product Rating'
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) desc
limit 5;

-- Q4 Compare the average purchase amounts between standard and express shipping.
SELECT shipping_type,
round(AVG(purchase_amount),2) as 'AVG Purchase Amount'
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

-- Q5 Do subscribed customers spend more compare to average spend and total revenue betweem subscribers and non-subscribers.   
SELECT subscription_status,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(sum(purchase_amount),2) as total_revenue
FROM customer
group by subscription_status
order by total_revenue, avg_spend desc;


-- Q6 Which 5 products have the highest percentage of purchases with discounts applied?
select  item_purchased,
ROUND(sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) * 100,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7 Segment customers into New, Returning, and Loyal based on their total number of previous purchases & show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case 
 when previous_purchases = 1 then 'New'
 when previous_purchases between 2 and 10 then 'Returning'
 else 'Loyal'
 end as customer_segment
from customer
 )
select customer_segment, count(*) as Total_customer
from customer_type
group by customer_segment;


-- Q8 What are thye top 3 products within each category?
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(PARTITION BY category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Q9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;


-- Q10 What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer 
group by age_group
order by total_revenue desc;
